#Goal:  To Deploy the built images from CI Steps once the CI Workflow is Succeeded

name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - "advanced"
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Copy Example Env to main env
        run: cp .env.example .env
      - name: Docker Login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy the containers with Docker Compose
        run: |
          docker compose pull
          docker compose up -d
