name: DevSecOps

on:
  push:
    branches: [master]

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  dependency-check:
    uses: ./.github/workflows/dependency-scan.yml

  docker-checks:
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit

  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit

  code-tests:
    uses: ./.github/workflows/code-tests.yml

  push-to-docker-hub:
    uses: ./.github/workflows/docker-push.yml
    needs:
      [
        code-quality,
        code-tests,
        sonar-scan,
        docker-checks,
        dependency-check,
        sonar-scan,
        code-tests,
        secret-scanning,
      ]
    secrets: inherit
