name: DevSecOps

on:
  push:
    branches: [master]

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  dependency-check:
    uses: ./.github/workflows/dependency-scan.yml

  docker-checks:
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit

  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit
  #push-to-docker-hub:
