#Goal to check whether the application code coverage doesn't have security threats
name: Sonar Qube Scan

on:
  workflow_call:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{ secrets.SONAR_HOST_URL }}
